--------------------------------------------------------
--  DDL for Table AKCHAT_MEMBERS
--------------------------------------------------------

  CREATE TABLE "NIBANAUSER"."AKCHAT_MEMBERS" 
   (	"REF_NO" NUMBER, 
	"INFO_REF_NO" NUMBER, 
	"ZUSER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_NIBANADB" ;
--------------------------------------------------------
--  Constraints for Table AKCHAT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "NIBANAUSER"."AKCHAT_MEMBERS" MODIFY ("REF_NO" NOT NULL ENABLE);
 
  ALTER TABLE "NIBANAUSER"."AKCHAT_MEMBERS" MODIFY ("INFO_REF_NO" NOT NULL ENABLE);
 
  ALTER TABLE "NIBANAUSER"."AKCHAT_MEMBERS" MODIFY ("ZUSER" NOT NULL ENABLE);
