--------------------------------------------------------
--  DDL for Table AKCHAT_USERS
--------------------------------------------------------

  CREATE TABLE "NIBANAUSER"."AKCHAT_USERS" 
   (	"USER_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MOBILE" NUMBER, 
	"CHECKOUT" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_NIBANADB" ;
--------------------------------------------------------
--  DDL for Index AKCHAT_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIBANAUSER"."AKCHAT_USERS_PK" ON "NIBANAUSER"."AKCHAT_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_NIBANADB" ;
--------------------------------------------------------
--  Constraints for Table AKCHAT_USERS
--------------------------------------------------------

  ALTER TABLE "NIBANAUSER"."AKCHAT_USERS" ADD CONSTRAINT "AKCHAT_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_NIBANADB"  ENABLE;
 
  ALTER TABLE "NIBANAUSER"."AKCHAT_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NIBANAUSER"."AKCHAT_USERS" MODIFY ("NAME" NOT NULL ENABLE);
